name: Call Reusable Matrix Docker pull

on: 
  push:
    branches: [ main ]

jobs:
  call_workflow:
    uses: zefirnikolov/reusable-pull-image-workflow/.github/workflows/matrix-docker-pull.yaml@main
    