name: Call Reusable OUTPUT DEMO.

on: 
  push:
    branches: [ main ]

jobs:
  call_workflow:
    uses: zefirnikolov/reusable-pull-image-workflow/.github/workflows/calculate-version-artifacts.yaml@main
    with:
      docker-image: alpine
      stage: stag
      release-version: "0.0.1"
      
  second:
    needs: [call_workflow]
    uses: zefirnikolov/reusable-pull-image-workflow/.github/workflows/create-helm-chart-artifacts.yaml@main
    with:
      docker-image: alpine
